WudFilmApp/WudFilmApp/Models/ModalFooter.cs
namespace WudFilmApp.Models
{
    public class ModalFooter
    {
        public string SubmitButtonText { get; set; } = "Submit";
        public string CancelButtonText { get; set; } = "Cancel";
        public string SubmitButtonID { get; set; } = "btn-submit";
        public string CancelButtonID { get; set; } = "btn-cancel";
        public bool OnlyCancelButton { get; set; }
    }
}

WudFilmApp/WudFilmApp/Models/ModalHeader.cs
namespace WudFilmApp.Models
{
    public class ModalHeader
    {
        public string Heading { get; set; }
    }
}

WudFilmApp/WudFilmApp/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WudFilmApp.Models;

namespace WudFilmApp.Controllers
{

    public class MoviesController : Controller
    {
        private readonly WudFilmAppContext _context;

        public MoviesController(WudFilmAppContext context)
        {
            _context = context;
        }

        // GET: Movies (admin only)
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            List<Movie> x = await _context.Movie.Include(m => m.Showtimes).ToListAsync();
            sortMovies(x);
            return View(x);
        }

        // GET: Movies/Listing
        [AllowAnonymous]
        public async Task<IActionResult> Listing()
        {
            List<Movie> x = await _context.Movie.Include(m => m.Showtimes)
                .Where(m => m.Showtimes != null && m.Showtimes.Any(s => s.HasShowtimePassed == false)).ToListAsync();
            sortMovies(x);

            var items = new List<MovieListItem>();
            x.ForEach(m => items.Add(new MovieListItem(m, m.Showtimes.First())));

            return View(items);
        }

        private void sortMovies(List<Movie> Movies)
        {
            Movies.OrderBy(m => m.Showtimes.Min(s => s.ShowDateTime));
        }



        // GET: Movies/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // include showtimes so that they display on details page
            var movie = await _context.Movie.Include(m => m.Showtimes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,PosterUrl,Subcommittee")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,PosterUrl,Subcommittee")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }



        // GET: Movies/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }
    }
}

WudFilmApp/WudFilmApp/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WudFilmApp.Areas.Identity.Data;
using WudFilmApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace WudFilmApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<RoleListModel> model = new List<RoleListModel>();
            model = roleManager.Roles.Select(r => new RoleListModel
            {
                RoleName = r.Name,
                Id = r.Id,
            }).ToList();
            return View(model);
        }

        // get and post for ADD & EDIT role
        [HttpGet]
        public async Task<IActionResult> AddEditApplicationRole(string id)
        {
            ApplicationRoleViewModel model = new ApplicationRoleViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                IdentityRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    model.Id = applicationRole.Id;
                    model.RoleName = applicationRole.Name;
                }
            }
            return PartialView("_AddEditApplicationRole", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEditApplicationRole(string id, ApplicationRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool isExist = !String.IsNullOrEmpty(id);
                IdentityRole applicationRole = isExist ? await roleManager.FindByIdAsync(id) :
               new IdentityRole
               {
               };
                applicationRole.Name = model.RoleName;
                IdentityResult roleRuslt = isExist ? await roleManager.UpdateAsync(applicationRole)
                                                    : await roleManager.CreateAsync(applicationRole);
                if (roleRuslt.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        // get and post for DELETE Role
        [HttpGet]
        public async Task<IActionResult> DeleteApplicationRole(string id)
        {
            string name = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                IdentityRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    name = applicationRole.Name;
                }
            }
            return PartialView("_DeleteApplicationRole", name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteApplicationRole(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                IdentityRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    IdentityResult roleRuslt = roleManager.DeleteAsync(applicationRole).Result;
                    if (roleRuslt.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }
    }
}

WudFilmApp/WudFilmApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WudFilmApp.Models;

namespace WudFilmApp.Controllers
{
    public class TestController : Controller
    {
        private readonly WudFilmAppContext _context;

        public TestController(WudFilmAppContext context)
        {
            this._context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        // runs all tests
        public async Task<IActionResult> RunAllTests()
        {
            // movie tests
            var result = await TestAddMovie();

            // showtime tests

            // user tests

            
            return result;  
        }


        // completes a test
        public IActionResult Complete(string message)
        {
            SetTestResult(message);
            var view = View("Index");
            return view;
        }



        public async Task<IActionResult> TestAddMovie()
        {
            // create a new movie to be added
            var title = $"test_{DateTime.Now}";
            var result = "";
            var movie = new Movie()
            {
                Title = title,
                Subcommittee = Subcommittee.Alternative
            };

            try
            {
                var entry = _context.Add(movie);
                await _context.SaveChangesAsync();

                result = $"Truck added successfully.";

                _context.Remove(entry.Entity);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                result = $"Failed to add truck {e.Message};";

            }

            return RedirectToAction("Complete", routeValues: new { message = result });

        }

        private void SetTestResult(string result)
        {
            if (ViewData.ContainsKey("TestResult"))
            {
                ViewData.Remove("TestResult");
            }

            ViewData.Add("TestResult", result);
        }
    }

}

WudFilmApp/WudFilmApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WudFilmApp.Areas.Identity.Data;
using WudFilmApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace WudFilmApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<WudFilmAppUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<WudFilmAppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }


        // index page of user list
        
        [HttpGet]
        public IActionResult Index()
        {
            List<UserListViewModel> model = new List<UserListViewModel>();
            model = userManager.Users.Select(u => new UserListViewModel
            {
                Id = u.Id,
                //Name = u.Name,
                Email = u.Email
                
            }).ToList();
            return View(model);
        }


        // edit user
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            EditUserViewModel model = new EditUserViewModel();
            model.ApplicationRoles = roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            if (!String.IsNullOrEmpty(id))
            {
                WudFilmAppUser user = await userManager.FindByIdAsync(id);
                if (user != null)
                {
                    //model.Name = user.Name;
                    model.Email = user.Email;
                    model.ApplicationRoleId = roleManager.Roles.Single(r => r.Name == userManager.GetRolesAsync(user).Result.Single()).Id;
                }
            }
            return PartialView("_EditUser", model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(string id, EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                WudFilmAppUser user = await userManager.FindByIdAsync(id);
                if (user != null)
                {
                    //user.Name = model.Name;
                    user.Email = model.Email;
                    string existingRole = userManager.GetRolesAsync(user).Result.Single();
                    string existingRoleId = roleManager.Roles.Single(r => r.Name == existingRole).Id;
                    IdentityResult result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        if (existingRoleId != model.ApplicationRoleId)
                        {
                            IdentityResult roleResult = await userManager.RemoveFromRoleAsync(user, existingRole);
                            if (roleResult.Succeeded)
                            {
                                IdentityRole applicationRole = await roleManager.FindByIdAsync(model.ApplicationRoleId);
                                if (applicationRole != null)
                                {
                                    IdentityResult newRoleResult = await userManager.AddToRoleAsync(user, applicationRole.Name);
                                    if (newRoleResult.Succeeded)
                                    {
                                        return RedirectToAction("Index");
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return PartialView("_EditUser", model);
        }

        // delete user
        [HttpGet]
        public async Task<IActionResult> DeleteUser(string id)
        {
            string email = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                WudFilmAppUser applicationUser = await userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    email = applicationUser.Email;
                }
            }
            return PartialView("_DeleteUser", email);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                WudFilmAppUser applicationUser = await userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    IdentityResult result = await userManager.DeleteAsync(applicationUser);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }
    }

    
}

WudFilmApp/WudFilmApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WUD Films</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/uw-style.css" />
        <link rel="stylesheet" href="~/css/uw-style-ie.css" />
        <link rel="stylesheet" href="~/css/fonts/uw160/fonts.0.0.1.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="uw-global-bar">
        <div class="container">
            <div class="uw-global-bar.uw-global-bar-inverse">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Movies" asp-action="Listing" class="navbar-brand">Wud Films</a>
            </div>
            <div class="uw-nav-menu-secondary">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@

                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
                    <li><a asp-area="" asp-controller="Movies" asp-action="Listing">Listing</a></li>
                    <li><a asp-area="" asp-controller="Showtimes" asp-action="Index">Showtimes</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
                    <li><a asp-area="" asp-controller="Role" asp-action="Index">Roles</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="Index">Test</a></li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WudFilmApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WudFilmApp/WudFilmApp/Views/Shared/_Modal.cshtml
@model WudFilmApp.Models.BootstrapModel

<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content">
        </div>
    </div>
</div>

WudFilmApp/WudFilmApp/Views/Shared/_ModalFooter.cshtml
@model WudFilmApp.Models.ModalFooter

<div class="modal-footer">
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        <button class="btn btn-success" id="@Model.SubmitButtonID" type="submit">            
               @Model.SubmitButtonText</button>
    }
</div>

WudFilmApp/WudFilmApp/Views/Shared/_ModalHeader.cshtml
@model WudFilmApp.Models.ModalHeader

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>