WudFilmApp/WudFilmApp/Areas/Identity/Pages/WUDFilmAppUsers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WudFilmApp.Areas.Identity.Authorization;
using WudFilmApp.Areas.Identity.Data;
using WudFilmApp.Models;

namespace WudFilmApp.Areas.Identity.Pages.WUDFilmAppUsers
{
    public class Create
    {
        public class CreateModel : WF_BasePageModel
        {
            public CreateModel(
                IdentityContext context,
                IAuthorizationService authorizationService,
                UserManager<IdentityUser> userManager)
                : base(context, authorizationService, userManager)
            {
            }

            public IActionResult OnGet()
            {
                WudFilmAppUser = new WudFilmAppUser
                {
                    NetID = "WUD",
                    Email = "WUD@wisc.edu"
                    
                };
                return Page();
            }

            [BindProperty]
            public WudFilmAppUser WudFilmAppUser { get; set; }

            
            public async Task<IActionResult> OnPostAsync()
            {
                if (!ModelState.IsValid)
                {
                    return Page();
                }

                WudFilmAppUser.OwnerID = UserManager.GetUserId(User);

                // requires using ContactManager.Authorization;
                var isAuthorized = await AuthorizationService.AuthorizeAsync(User, WudFilmAppUser, ContactOperations.Create);
                if (!isAuthorized.Succeeded)
                {
                    return new ChallengeResult();
                }

                Context.WudFilmAppUser.Add(WudFilmAppUser);
                await Context.SaveChangesAsync();

                return RedirectToPage("./Index");
            }
        }
    }
}

WudFilmApp/WudFilmApp/Areas/Identity/Pages/WUDFilmAppUsers/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WudFilmApp.Areas.Identity.Authorization;
using WudFilmApp.Areas.Identity.Data;
using WudFilmApp.Models;

namespace WudFilmApp.Areas.Identity.Pages.WUDFilmAppUsers
{
    public class DeleteModel : WF_BasePageModel
    {
        public DeleteModel(
           IdentityContext context,
           IAuthorizationService authorizationService,
           UserManager<IdentityUser> userManager)
           : base(context, authorizationService, userManager)
        {
        }

        [BindProperty]
        public WudFilmAppUser WFUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string NetID)
        {
            WFUser = await Context.WudFilmAppUser.FirstOrDefaultAsync(
                                                 m => m.NetID == NetID);

            if (WFUser == null)
            {
                return NotFound();
            }

            var isAuthorized = await AuthorizationService.AuthorizeAsync(
                                                     User, WFUser,
                                                     ContactOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string NetID)
        {
            WFUser = await Context.WudFilmAppUser.FindAsync(NetID);

            var contact = await Context
                .WudFilmAppUser.AsNoTracking()
                .FirstOrDefaultAsync(m => m.NetID.Equals(NetID));

            if (contact == null)
            {
                return NotFound();
            }

            var isAuthorized = await AuthorizationService.AuthorizeAsync(
                                                     User, contact,
                                                     ContactOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            Context.WudFilmAppUser.Remove(WFUser);
            await Context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WudFilmApp/WudFilmApp/Areas/Identity/Pages/WUDFilmAppUsers/Details.cshtml.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WudFilmApp.Areas.Identity.Authorization;
using WudFilmApp.Areas.Identity.Data;
using WudFilmApp.Models;

namespace WudFilmApp.Areas.Identity.Pages.WUDFilmAppUsers
{
    public class DetailsModel : WF_BasePageModel
    {
        public DetailsModel(
            IdentityContext context,
            IAuthorizationService authorizationService,
            UserManager<IdentityUser> userManager)
            : base(context, authorizationService, userManager)
        {
        }

        public WudFilmAppUser WFUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string NetID)
        {
            WFUser = await Context.WudFilmAppUser.FirstOrDefaultAsync(m => m.NetID.Equals(NetID));

            if (WFUser == null)
            {
                return NotFound();
            }

            var isAuthorized = User.IsInRole(Constants.ContactManagersRole) ||
                               User.IsInRole(Constants.ContactAdministratorsRole);

            var currentUserId = UserManager.GetUserId(User);

            if (!isAuthorized
                && currentUserId != WFUser.OwnerID
                && WFUser.Status != ContactStatus.Approved)
            {
                return new ChallengeResult();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string NetID, ContactStatus status)
        {
            var contact = await Context.WudFilmAppUser.FirstOrDefaultAsync(
                                                      m => m.NetID.Equals(NetID));

            if (contact == null)
            {
                return NotFound();
            }

            var contactOperation = (status == ContactStatus.Approved)
                                                       ? ContactOperations.Approve
                                                       : ContactOperations.Reject;

            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, WFUser,
                                        contactOperation);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }
            contact.Status = status;
            Context.WudFilmAppUser.Update(contact);
            await Context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WudFilmApp/WudFilmApp/Areas/Identity/Pages/WUDFilmAppUsers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WudFilmApp.Areas.Identity.Authorization;
using WudFilmApp.Areas.Identity.Data;
using WudFilmApp.Models;

namespace WudFilmApp.Areas.Identity.Pages.WUDFilmAppUsers
{
    public class EditModel : WF_BasePageModel
    {
        public EditModel(
            IdentityContext context,
            IAuthorizationService authorizationService,
            UserManager<IdentityUser> userManager)
            : base(context, authorizationService, userManager)
        {
        }

        [BindProperty]
        public WudFilmAppUser WFUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string NetID)
        {
            WFUser = await Context.WudFilmAppUser.FirstOrDefaultAsync(
                                             m => m.NetID == NetID);

            if (WFUser == null)
            {
                return NotFound();
            }

            var isAuthorized = await AuthorizationService.AuthorizeAsync(
                                                      User, WFUser,
                                                      ContactOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string OwnerID)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            /* Fetch Contact from DB to get OwnerID.
                var WFUser = await Context
                .WudFilmAppUser.AsNoTracking()
                .FirstOrDefaultAsync(m => m.OwnerID.Equals(OwnerID));

            if (WFUser == null)
            {
                return NotFound();
            }

            var isAuthorized = await IAuthorizationService.AuthorizeAsync(
                                                     User, WFUser,
                                                     ContactOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }*/

            WFUser.OwnerID = WFUser.OwnerID;

            Context.Attach(WFUser).State = EntityState.Modified;

            if (WFUser.Status == ContactStatus.Approved)
            {
                // If the contact is updated after approval, 
                // and the user cannot approve,
                // set the status back to submitted so the update can be
                // checked and approved.
                var canApprove = await AuthorizationService.AuthorizeAsync(User,
                                        WFUser,
                                        ContactOperations.Approve);

                if (!canApprove.Succeeded)
                {
                    WFUser.Status = ContactStatus.Submitted;
                }
            }

            await Context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        private bool ContactExists(string NetID)
        {
            return Context.WudFilmAppUser.Any(e => e.NetID.Equals(NetID));
        }
    }
}

WudFilmApp/WudFilmApp/Controllers/ShowtimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WudFilmApp.Models;

namespace WudFilmApp.Controllers
{
    public class ShowtimesController : Controller
    {
        private readonly WudFilmAppContext _context;

        public ShowtimesController(WudFilmAppContext context)
        {
            _context = context;
        }

        // GET: Showtimes
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var wudFilmAppContext = _context.Showtime.Include(s => s.Movie);
            return View(await wudFilmAppContext.ToListAsync());
        }

        // GET: Showtimes/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showtime = await _context.Showtime
                .Include(s => s.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (showtime == null)
            {
                return NotFound();
            }

            return View(showtime);
        }

        // GET: Showtimes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movie, "Id", "Title");
            return View();
        }

        // POST: Showtimes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MovieId,ShowDateTime")] Showtime showtime)
        {
            if (ModelState.IsValid)
            {
                _context.Add(showtime);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movie, "Id", "Title", showtime.MovieId);
            return View(showtime);
        }

        // GET: Showtimes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showtime = await _context.Showtime.FindAsync(id);
            if (showtime == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movie, "Id", "Title", showtime.MovieId);
            return View(showtime);
        }

        // POST: Showtimes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieId,ShowDateTime")] Showtime showtime)
        {
            if (id != showtime.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(showtime);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowtimeExists(showtime.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movie, "Id", "Title", showtime.MovieId);
            return View(showtime);
        }

        // GET: Showtimes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showtime = await _context.Showtime
                .Include(s => s.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (showtime == null)
            {
                return NotFound();
            }

            return View(showtime);
        }

        // POST: Showtimes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var showtime = await _context.Showtime.FindAsync(id);
            _context.Showtime.Remove(showtime);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowtimeExists(int id)
        {
            return _context.Showtime.Any(e => e.Id == id);
        }
    }
}

WudFilmApp/WudFilmApp/Views/Movies/Create.cshtml
@model WudFilmApp.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PosterUrl" class="control-label"></label>
                <input asp-for="PosterUrl" class="form-control"/>
                <span asp-validation-for="PosterUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label"></label>
                <input asp-for="Format" class="form-control"/>
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control"/>
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subcommittee" class="control-label"></label>
                <select asp-for="Subcommittee" class="form-control" asp-items="Html.GetEnumSelectList<Subcommittee>()"></select>
                <span asp-validation-for="Subcommittee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WudFilmApp/WudFilmApp/Views/Movies/Delete.cshtml
@model WudFilmApp.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subcommittee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subcommittee)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WudFilmApp/WudFilmApp/Views/Movies/Details.cshtml
@model WudFilmApp.Models.Movie

@{
    ViewData["Title"] = $"{@Model.Title}";
}
<img src="@Model.PosterUrl" alt="No Image"
     style="width: 100px; height: 150px; "/>
<h2>@Model.Title</h2>

<div >

   
    <dl class="dl-horizontal">
 
        <dt>
            @Html.DisplayNameFor(model => model.Subcommittee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subcommittee)
        </dd>
        <dt>
            Showtimes
        </dt>
        <dd>
            <table class="table">
                <thead>
                <tr>
                    
                    <th>
                        ShowTime
                    </th>
                    <th>
                       Has Showtime Passed
                    </th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <!--Display the list of showtimes here -->
                @foreach (var item in Model.Showtimes ?? new List<Showtime>())
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.ShowDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HasShowtimePassed)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" asp-controller="Showtimes">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id" asp-controller="Showtimes">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id" asp-controller="Showtimes">Delete</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WudFilmApp/WudFilmApp/Views/Movies/Edit.cshtml
@model WudFilmApp.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label"></label>
                <input asp-for="Format" class="form-control"/>
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control"/>
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PosterUrl" class="control-label"></label>
                <input asp-for="PosterUrl" class="form-control"/>
                <span asp-validation-for="PosterUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subcommittee" class="control-label"></label>
                <select asp-for="Subcommittee" class="form-control" asp-items="Html.GetEnumSelectList<Subcommittee>()"></select>
                <span asp-validation-for="Subcommittee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WudFilmApp/WudFilmApp/Views/Movies/Index.cshtml
@model IEnumerable<WudFilmApp.Models.Movie>

@{
    ViewData["Title"] = "Now Playing";
}

<h2>Now Playing</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subcommittee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Runtime)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            <img src="@item.PosterUrl" alt="No Image" style="width: 100px; height: 150px;"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subcommittee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Runtime)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
    </tr>
}
    </tbody>
</table>

WudFilmApp/WudFilmApp/Views/Movies/Listing.cshtml
@model IEnumerable<WudFilmApp.Models.MovieListItem>

@{
    ViewData["Title"] = "Now Showing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/movie.css" />
<h2>Now Showing</h2>


<div class="body-content">
    <ul class="movie-list">

        @foreach (var item in Model)
        {

            <li class="movie-item">
                <a asp-action="Details" asp-route-id="@item.Movie.Id">
                    <div class="movie-background">
                        <img src="@item.PosterUrl" class="movie-poster" alt-text="@item.Title" />
                        <div class="movie-details">
                            <h3 class="movie-title">@Html.DisplayFor(modelItem => item.Title)</h3>
                            <p class="showtime-info">@Html.DisplayFor(modelItem => item.AdditionalInfo)</p>
                        </div>

                    </div>
                </a>
            </li>


        }
    </ul>
</div>